# Generated by Django 4.2 on 2024-01-19 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='ホテル名')),
                ('description', models.TextField(verbose_name='説明')),
                ('price_range', models.CharField(max_length=20, verbose_name='価格帯')),
                ('max_capacity', models.CharField(blank=True, max_length=127, verbose_name='定員')),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('zip_number', models.CharField(blank=True, max_length=20, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=60, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=127, unique=True)),
                ('category', models.CharField(max_length=20, null=True, verbose_name='カテゴリ')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='写真')),
                ('average', models.FloatField(default=0.0, verbose_name='平均点')),
                ('rounded_avg', models.FloatField(default=0.0, verbose_name='丸めた平均点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Hotel',
            },
        ),
    ]
