# Generated by Django 4.2 on 2024-01-29 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='チェックイン')),
                ('check_out', models.DateField(verbose_name='チェックアウト')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.hotel', verbose_name='ホテル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Reservation',
                'db_table': 'Reservation',
            },
        ),
    ]
